data:
  raw_path: data/raw/
  processed_path: data/processed/

preprocessing:
  scale_method: standard  # options: standard, minmax, robust
  fill_missing: mean      # options: mean, median, zero
  encoder: LabelEncoder # options: OneHotEncoder
model:
  type: autoencoder       # options: autoencoder, isolation_forest, one_class_svm
  latent_dim: 16
  epochs: 50
  batch_size: 64
  learning_rate: 0.001

deployment:
  host: 0.0.0.0
  port: 8501
